#!/bin/bash
set -e

function _symlink {
  local src_path=$1
  local dest_path=$2

  if [ -L $dest_path ]; then
    echo "+ $dest_path is already symlinked"
  else
    if [ -f $dest_path ]; then
      # Rename existing file before symlinking
      local renamed="$dest_path.pre-dotfiles"
      echo "+ Renaming $dest_path -> $renamed"
      mv $dest_path $renamed
    fi

    echo "+ Symlink $dest_path"
    ln -sf $src_path $dest_path
  fi
}
