cask_args appdir: '/Applications'

brew 'colima'
brew 'maven'
brew 'neovim'
brew 'tmux'
brew 'volta'
brew 'z'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'alacritty'
cask 'corretto'

# brew 'git'
# brew 'vim'
# brew 'z'
# brew 'zsh'
# brew 'zsh-autosuggestions'
# brew 'zsh-completions'
# brew 'zsh-syntax-highlighting'

# cask 'alfred'
# cask 'firefox'
# cask 'iterm2'
# cask 'notion'
# cask 'rectangle'
# cask 'slack'
# cask 'spotify'
# cask 'visual-studio-code'
