#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../bash_helpers

# Install vim-plug
if [ -f ~/.vim/autoload/plug.vim ]; then
  echo "+ vim-plug is already installed"
else
  echo "+ Installing vim-plug..."
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Symlink .vimrc
_symlink $DIR/vimrc ~/.vimrc

# Symlink nvim config
if [ -d ~/.config/nvim/autoload ]; then
  echo "+ nvim config already set up"
else
  echo "+ Symlink nvim config"
  mkdir -p ~/.config/nvim/autoload
  ln -sf $DIR/vimrc ~/.config/nvim/init.vim
  ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/
fi
