#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Install vim-plug
echo "+ Installing vim-plug..."
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Symlink vimrc
echo "+ Symlinking .vimrc"
ln -sf $DIR/vimrc ~/.vimrc

# Symlink nvim config
echo "+ Symlink nvim config"
mkdir -p ~/.config/nvim/autoload
ln -sf $DIR/vimrc ~/.config/nvim/init.vim
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/
