#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
mkdir -p $HOME/.config

# Symlink configuration files & directories
ln -s $DIR/.tmux.conf $HOME/.tmux.conf
ln -s $DIR/alacritty $HOME/.config/alacritty
ln -s $DIR/nvim $HOME/.config/nvim

echo "Symlinked configuration files & directories"
