#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../bash_helpers

# Set zsh as default shell
if [ $(which $SHELL) != '/bin/zsh' ]; then
  echo "+ Setting zsh as default shell"
  chsh -s /bin/zsh
else
  echo "+ Default shell already zsh"
fi

# Install Oh My Zsh
if [ -d ~/.oh-my-zsh ]; then
  echo "+ Oh My Zsh already installed"
else
  echo "+ Installing Oh My Zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Symlink .zshrc
_symlink $DIR/zshrc ~/.zshrc

# Install Pure prompt
if type npm >/dev/null 2>&1; then
  if ! npm list --depth 1 --global pure-prompt > /dev/null 2>&1; then
    echo "+ Installing Pure prompt"
    npm install --global pure-prompt
  else
    echo "+ Pure prompt already installed"
  fi
else
  echo "! Install pure-prompt manually via npm"
fi
