# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [ -f $HOME/.zshrc.before.local ]; then
  source $HOME/.zshrc.before.local
fi

# Oh My Zsh configuration
# ---------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git vagrant deno)
source $ZSH/oh-my-zsh.sh

# # Pure prompt
# # ---------------------------------------
# fpath+=("$HOME/.zsh/pure")
# autoload -U promptinit; promptinit
# prompt pure

# Environment variables
# ---------------------------------------
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Key bindings
# ---------------------------------------
bindkey '§' autosuggest-accept
bindkey '[C' forward-word
bindkey '[D' backward-word
bindkey '^H' backward-kill-word
# bindkey '^[^?' backward-kill-word

# Aliases
# ---------------------------------------
alias x="exit"
alias l="ls -la"
alias ..="cd .."
alias ...="cd ../.."
alias gs="git status"
alias gaa="git add --all"
alias gpl="git pull"
alias gph="git push"
alias gphf="git push --follow-tags"
alias gc="git commit -v"
alias gcn="git commit -v --no-verify"
alias vim="nvim"
alias c="code ."
alias cx="code . && exit"
alias gcz="git cz"
alias oni="/Applications/Onivim2.App/Contents/MacOS/Oni2"

# Functions
# ---------------------------------------
# Start a web server for the specified directory
function simple-server() {
  local dir=$1
  (cd $dir && python -m SimpleHTTPServer 8000)
}

# Plugins
# ---------------------------------------
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=true

# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

#   autoload -Uz compinit
#   compinit
# fi

fpath=(/usr/local/share/zsh-completions $fpath)

. /opt/homebrew/etc/profile.d/z.sh

# This speeds up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238 (specifically comment #issuecomment-389324292)
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# Computer-specific overrides
# ---------------------------------------
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

if [ -f $HOME/.zshrc.tmux ]; then
  source $HOME/.zshrc.tmux
fi

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# bun completions
[ -s "/Users/jwet/.bun/_bun" ] && source "/Users/jwet/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
