#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Install packages
echo "+ Installing Atom packages..."
apm install --packages-file $DIR/packages.txt

# Symlink config files
echo "+ Symlinking Atom config files"
for f in $DIR/.atom/*
do
  ln -sf $f ~/.atom
done
