#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Install oh-my-fish
if type omf >/dev/null 2>&1; then
  echo "+ Installing oh-my-fish..."
  curl -L https://get.oh-my.fish | fish
else
  echo "+ oh-my-fish already installed"
fi

# Symlink config files
echo "+ Symlinking fish config files"
for f in $DIR/omf/*
do
  ln -sf $f $OMF_CONFIG
done
