#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Activating Fish shell
FISH=$(which fish)

if [ $SHELL != $FISH ]; then
  echo "+ Hello"

  # TODO Verify this check
  if !(grep -q $FISH /etc/shells); then
    echo "+ Appending Fish to /etc/shells"
    which fish | sudo tee -a /etc/shells
  fi

  echo "+ Activating Fish shell"
  chsh -s $FISH
fi

# TODO Fix this check
# Install oh-my-fish
if ! type omf >/dev/null 2>&1; then
  echo "+ Installing oh-my-fish..."
  curl -L https://get.oh-my.fish | fish
fi

# Symlink config files
echo "+ Symlinking fish config files"
for f in $DIR/omf/*
do
  ln -sf $f $OMF_CONFIG
done

# Enable fzf key bindings
/usr/local/opt/fzf/install
